class YoutubeMaster:
    def __init__(self):
        self.api_key = "AIzaSyAjbf9cg4eT384Gv21LpsM87qIIgj3wpK8"
        self.youtube_api_service_name = u'youtube'
        self.youtube_api_version = u'v3'
        self.iso_english_code = u'en'
        self.items = u'items'
        self.snippet = u'snippet'
        self.content_details = u'contentDetails'
        self.licensed_content = u'licensedContent'
        self.statistics = u'statistics'
        self.status = u'status'
        self.channel_title = u'channelTitle'
        self.channel_id = u'channelId'
        self.title = u'title'
        self.id = u'id'
        self.video_url = u'video_url'
        self.published_at = u'publishedAt'
        self.duration = u'duration'
        self.license = u'license'
        self.view_count = u'viewCount'
        self.like_count = u'likeCount'
        self.category_id = u'categoryId'
        self.description = u'description'
        self.thumbnails = u'thumbnails'
        self.transcripts = u'transcripts'
        self.localised = u'localized'
        self.default_audio_language = u'defaultAudioLanguage'
        self.playlist_id = u'playlistId'
        self.next_page_token = u'nextPageToken'
        self.resource_id = u'resourceId'
        self.subscriber_count = u'subscriberCount'
        self.related_playlists = u'relatedPlaylists'
        self.custom_url = u'customUrl'
        self.video_count = u'videoCount'
        self.uploads = u'uploads'
        self.item_count = u'itemCount'
        self.video_id = u'videoId'
        self.default = u'default'
        self.url = u'url'


